theme: minima
title: My JavaScript Learning Progress Blog
author: Marshall Okafor
description: I have always wanted to learn JavaScript. I am excited about this experience and can not wait to roll up my sleeves. I will be using this blog to discuss my progress.
